name: 'Hello World'
description: 'Greet someone'
inputs:
  repo:  # id of input
    description: 'Repository to update'
    required: true
  token:
    description: 'github tocken with read access to the repository'
    required: true
  ref:
    description: Branch to update
    required: false
    default: ''
  changes:
    required: true
    description: "Content to modify"
  slack-webhook:
    required: false
    description: "Webhook for the notification (disabled if not specified)"

  commit-message:
    required: false
    description: "Commit message"
    default: "New version"
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}

    - uses: chrisdickinson/setup-yq@latest
    
    # --- change needed files --- #
    - id: update
      name: Update docker-compose files
      run: |
        JSON_INPUT=$CHANGES

        # Json format [{"path": "my-deployment", "service": "my-service", image: "my-image"}]
        #JSON_INPUT='[{"path": "examples/my-deplyment", "service": "my-service", "image": "my-image:v123"}]'

        echo "::set-output name=message-title::*Version updated :*"

        message="*New versions :* \n"


        function update_image() {
          local row="$1"
          local decoded=$(echo "$row" | base64 --decode)
          _jq() {
            echo "$decoded" | jq -r "$1"
          }

          local path
          local service
          local image

          path=$(_jq '.path')
          service=$(_jq '.service')
          image=$(_jq '.image')

          yq -i ".services.$service.image = \"$image\"" "$path/docker-compose.yml"
          message="$message- $path [$service] => $image\n"
        }

        for row in $(echo "$JSON_INPUT" | jq -r '.[] | @base64'); do
          update_image "$row"
        done

        echo "::set-output name=message::$message"
      shell: bash
      env:
        CHANGES: ${{ inputs.changes }}

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actor
        message: ${{ inputs.commit-message}}

    - if: ${{ inputs.slack-webhook }}
      name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        SLACK_ICON: ":rocket:"
        SLACK_MESSAGE: ${{ steps.update.outputs.message }}
        SLACK_TITLE: ${{ steps.update.outputs.message-title }}
        SLACK_FOOTER: ""

